name: Build and Test
description: Checkout, install dependencies, build the application, and run unit tests.

inputs:
  base-path:
    description: Vite base path for the build (e.g. /programmedev/)
    required: false
    default: /

runs:
  using: composite
  steps:
  - name: Setup Node.js
    uses: actions/setup-node@v6
    with:
      node-version: "lts/*"
      cache: "npm"

  - name: Install dependencies
    run: npm ci
    shell: bash

  - name: Build application
    run: npm run build -- --base=${{ inputs.base-path }}
    shell: bash

  - name: Run unit tests
    run: npx vitest run --reporter=default --reporter=junit --outputFile.junit=unit-test-results.xml
    shell: bash

  - name: Publish unit test results
    uses: dorny/test-reporter@v2
    if: always()
    with:
      name: Unit Tests
      path: unit-test-results.xml
      reporter: java-junit
